### PR TITLE
Feat: headers in generated ifc files

### PR DESCRIPTION
**Pull request by D4ve-R**
## Changes:
* Add ifc schemas to ifc-schema.ts
* Add ifcjs header comment for new ifc files
* Add headerline FILE_NAME & FILE_DESCRIPTION to header
* Fix WriteHeaderLine in web-ifc-api.cpp to not write double sets
* Add missing ExportFileAsIFC as deprecated
* Tests

## New IFC Headers

Bildschirmfoto 2023-02-14 um 16 20 38

### CODE REVIEW

**Comment by D4ve-R** [comment]
resolves #337

**Comment by beachtom** [comment]
@D4ve-R thanks for this - did you see my two comments?

**Comment by D4ve-R** [comment]
@beachtom, no i didn't, which comments do you mean ?

**Comment by beachtom** [comment]
Two comments in the source - asking if you can just sync up how the debug build and the release build work i.e. implement the changes in package.json to both.

Also I was wondering should the +512 be applied in the Loader or the web-ifc-api.cpp instead of the TS

**Comment by D4ve-R** [comment]
Done!
I had to add the 512 because otherwise this line :
https://github.com/IFCjs/web-ifc/blob/300c9bc184bfe51a00806a48dba09c70e114f079/src/web-ifc-api.ts#L249
would crash, because `src` is be bigger than `dataBuffer`.   
It might be useful to apply it in cpp, but i think the way it is handled in ts right now is fine, since the buffer is shrunk down to real size later.

Maybe this should be a parameter, because some parts of the headerlines are arrays, so this could become an issue  again.
Handling it in cpp might help to determine real size.

**Comment by beachtom** [comment]
@D4ve-R agree - I will mark this to look at later - I will accept now - thanks!

**Pull request merged**
