### PR TITLE
Fix for #285.

### PR DESCRIPTION
**Pull request by pablo-mayrgundter**
I couldn't figure out the type signature so I parse the key to number.

Also there's an existing functional test for this, but NB a bunch of other tests currently aren't passing.

### CODE REVIEW

**Comment by beachtom** [comment]
@pablo-mayrgundter  looks like I didn't fix this method properly when converting to the new schema types. But thank it looks like you fixed it - it is all working at my end

**Comment by QuimMoya** [comment]
I only found a minor issue in the example/Usage, once solved i will accept the PR

**Comment by pablo-mayrgundter** [comment]
> I only found a minor issue in the example/Usage, once solved i will accept the PR

From this PR?  The change adding the newline in the examples?  I tried backing that out but git doesn't want to accept that edit for some reason.  Not sure how to remove that file from the PR but will figure it out if that's the issue

**Comment by QuimMoya** [comment]
Maybe it comes from a previous issue, i will try to solve myself.

**Pull request merged**
