### PR TITLE
Added Z shapeProfileDef

### PR DESCRIPTION
**Pull request by engthiago**
Added Support for Z Shape Profiles, following the same code structure as other parametric profiles added earlier
zprof

### CODE REVIEW

**Comment by beachtom** [comment]
@engthiago FYI not ignoring this - just doing hefty work on geometry in another branch and just waiting on that to finish first.

**Comment by engthiago** [comment]
@beachtom thanks, There are some more more pull requests that I am intending to create shortly

**Comment by QuimMoya** [comment]
@engthiago Sorry for the delay

**Review by QuimMoya — COMMENTED** [review]
It's fine

**Pull request merged**
