### PR TITLE
Adding Support for Multiple IFC Schemas

### PR DESCRIPTION
**Pull request by beachtom**
This PR Does several things:
-Cleans up the schema generation code
-Add support for multiple IFC schemas - so we can now parse correctly IFC2X3 and IFC4 and have all the correct properties available.
-Add support for inheritance so we can ask for all instances of a type - but also all instances that are of the type or inherit from the type
-Cleanup the properties helper to use the inverse functionality and also support multi schema

### CODE REVIEW

**Comment by QuimMoya** [comment]
@beachtom 

Hello
Great work!!
I would like to know how it works exactly before accepting it, can we meet?

**Comment by beachtom** [comment]
@QuimMoya yes sure - how do you want to connect?

**Comment by QuimMoya** [comment]
@beachtom 

First i will study it a few. Then we can meet. Are you on discord?

**Comment by beachtom** [comment]
Yes I am tombeach

**Comment by agviegas** [comment]
Hey @TxTony did you check [this](https://github.com/IFCjs/test-ifc-files) out?

**Comment by QuimMoya** [comment]
@beachtom
Excellent work

**Pull request merged**
