### PR TITLE
Rename LogLevel enum names to LOG_LEVEL_XXXX

### PR DESCRIPTION
**Pull request by jespa007**
@beachtom here there're the PR about the issue of LogLevel enum.

### CODE REVIEW

**Comment by beachtom** [comment]
Great! Thanks. There is also an ENUM is the web-ifc-api.ts - can we change that so it matches?

**Comment by jespa007** [comment]
> Great! Thanks. There is also an ENUM is the web-ifc-api.ts - can we change that so it matches?

I thought to do that but in the end I didn't due the isse it is NOT in the `typescript` side, it's on the C++ `side`. So better cancel this pull request and redo a PR with also the typescript modifications

**Comment by beachtom** [comment]
You should just be able to repush to the branch and it should update

**Comment by jespa007** [comment]
@beachtom updated LogLevel for typescript tooo :-)

**Pull request merged**
