### PR TITLE
Log control

### PR DESCRIPTION
**Pull request by pablo-mayrgundter**
This PR introduces configurable control of logging levels: DEBUG, INFO, WARN, ERROR, OFF.  This is used to optionalize the version logging, i.e. to disable for jsconsole and unit tests.

NOTE: I'm debugging an issue where setting the log level from the TS wrapper doesn't take effect.

### CODE REVIEW

**Comment by pablo-mayrgundter** [comment]
Hi @agviegas, this is ready for review!

**Comment by aka-blackboots** [comment]
@pablo-mayrgundter, I'm unable to build the release.

Error
`./src/wasm/web-ifc-api.cpp:701:1: error: expected unqualified-id
)
^
./src/wasm/web-ifc-api.cpp:822:42: error: use of undeclared identifier 'SetLogLevel'
    emscripten::function("SetLogLevel", &SetLogLevel);`

**Comment by pablo-mayrgundter** [comment]
Hi @QuimMoya, it looks like the error you had seen was not related to this PR.

Shall I resubmit?

**Comment by agviegas** [comment]
@pablo-mayrgundter yes please!

**Pull request merged**
