### PR TITLE
web-ifc versioning

### LINKED ISSUE #308: web-ifc versioning
Hi there,

I post this issue as a Best Practice in the software. Latelly, I've seen that web-ifc has a lot of "commits" in the "main" branch but it package.json keeps the same version (i.e 0.0.36). 

I'd would recommend to create a [milestone](https://docs.github.com/en/issues/using-labels-and-milestones-to-track-work/about-milestones) organize and generate versions for a set of issues than people publishes.

Then people can compare better the software within diferents versions.

Also I can see that, there's no any web-ifc release published yet in the releases github section.

image

### PR DESCRIPTION
**Pull request by D4ve-R**
# New publish workflow: 
 * triggers on release create
 * build the complete project using `npm run build-publish-repo` from package.json
 * publish to npm, assumes npm account name is same as org/user name of repo
 * assumes repo has a secret `NPM_TOKEN`, used to auth with npm registry

<hr/>

## config:
- [ ] create repository [secret](https://docs.github.com/de/actions/security-guides/encrypted-secrets) `NPM_TOKEN` with [npm access token](https://docs.npmjs.com/creating-and-viewing-access-tokens) for ifcjs

## usage:
- [ ] create new release with [auto generated notes](https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes)
- [ ] (optional) add wasm files to release
    
<hr/>
I propose to add a new minor release like 0.0.X every 5-10 merged PRs.  
 
⚠️ when merging, please use squash merge, it got a bit messy testing out gh actions 

resolves #308

### CODE REVIEW

**Comment by agviegas** [comment]
Hey, thanks a lot for this! We look forward to trying this out. One question: would it be possible to create a git tag + release notes with this?

**Comment by D4ve-R** [comment]
I will look into this, i'm sure that's possible somehow

**Comment by beachtom** [comment]
Thanks for this - I was actually thinking of something similar. @agviegas  to use this we will need to set up the repo to auth against npm

**Comment by beachtom** [comment]
@D4ve-R  - looking at this - will we not need to first build the artefacts i.e. the wasm to publish to NPM? I created a workflow to build the demo viewer automatically could we look at that?

**Comment by agviegas** [comment]
Hey @beachtom I think I've given you full access to the repository. Otherwise, @QuimMoya could also take a look into this.

**Comment by D4ve-R** [comment]
@beachtom, yes sure, i just wanted to make something work with the existing scripts from package.json.
Shall i drop, so you can take the issue ?

**Comment by beachtom** [comment]
Happy to take but - I think all we need to do is add the EMSCRIPTEM environment. I think we just need to add 

 - uses: mymindstorm/setup-emsdk@v11
        with:
          version: 3.1.31

to the yml

**Comment by D4ve-R** [comment]
Alright, sorry misunderstood you there, i'm not that experienced with emscripten

**Comment by beachtom** [comment]
@D4ve-R  - this now looks great thanks. I will hold this for now until I get the AUTH token sorted then I will merge

**Pull request merged**
