### PR TITLE
Fix incorrect normals on some faces #536

### PR DESCRIPTION
**Pull request by szamocza**
This is a bugfix that will likely fix a lot of other issues, so it's worth checking out the long-standing geometries bugs.

### CODE REVIEW

**Comment by beachtom** [comment]
Thanks for this. I am just running the tests - then I will approve assuming all is OK

**Comment by beachtom** [comment]
Does this close #536 by the way

**Comment by szamocza** [comment]
> Does this close #536 by the way

Yes is does. And I think it solves #306 and maybe others too due to the fundamental nature of the problem.
I tested it only from native c++ code, I have not set up the the build environment yet.

**Comment by beachtom** [comment]
Just need to check why some models regressions results are changing then I will merge - it is probably good changes!

**Pull request merged**
